const BatallaPalabras=(()=>{const $=id=>document.getElementById(id);let mode="normal",teams=[],round=1,rounds=10,time=30,goal=0,active=0,score=[],timer=null,endsAt=0,current=null,lastAnswer="",categoryFilter="Todas";
const modes=[{id:"normal",name:"Normal",desc:"Responde cualquier palabra válida de la categoría."},{id:"letra",name:"Letra",desc:"Tu respuesta debe empezar con la letra indicada."},{id:"cadena",name:"Cadena",desc:"Tu respuesta debe empezar con la última letra válida."},{id:"rapido",name:"Rápido",desc:"El reloj baja de tiempo en cada ronda."},{id:"supervivencia",name:"Supervivencia",desc:"Un fallo o el tiempo agotado resta 1 punto."}];
const letters="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ".split(""),DB=window.AMS_NEW_GAMES_DB?.batalla?.categories||{},categories=Object.keys(DB);
const esc=s=>window.Utils?.escapeHTML?window.Utils.escapeHTML(s):String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function save(screen="bp-scr-lobby"){window.GameSession?.save("batalla",{mode,teams,round,rounds,time,goal,active,score,endsAt,current,lastAnswer,categoryFilter,screen,savedAt:Date.now()})}
function screen(id){["bp-scr-lobby","bp-scr-game","bp-scr-result"].forEach(x=>$(x).hidden=x!==id);save(id);renderScore()}
function renderModes(){$("bp-modes").innerHTML=modes.map(m=>`<button type="button" class="bp-mode ${m.id===mode?"selected":""}" data-mode="${m.id}"><strong>${m.name}</strong><small>${m.desc}</small></button>`).join("")}
function renderCategories(){$("bp-category-filter").innerHTML=[`<option value="Todas">Todas las categorías</option>`,...categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`)].join("");$("bp-category-filter").value=categoryFilter}
function renderTeamInputs(){const n=Number($("bp-teams").value);$("bp-team-inputs").innerHTML=Array.from({length:n},(_,i)=>`<label>Equipo ${i+1}<input id="bp-team-${i}" maxlength="22" value="${esc(teams[i]||"Equipo "+(i+1))}" placeholder="Nombre del equipo"></label>`).join("")}
function newChallenge(){const list=categoryFilter==="Todas"?categories:[categoryFilter],category=list[Math.floor(Math.random()*list.length)]||categories[0],pool=DB[category]||[],target=pool[Math.floor(Math.random()*pool.length)]||"";let letter=letters[Math.floor(Math.random()*letters.length)];if(mode==="cadena"&&lastAnswer)letter=lastAnswer.trim().slice(-1).toUpperCase();current={category,letter,target,chainLast:lastAnswer};$("bp-category").textContent=category;$("bp-letter").textContent=mode==="normal"?"":letter;$("bp-letter").style.display=mode==="normal"?"none":"block";$("bp-hint").textContent=mode==="normal"?"Di una palabra que pertenezca a la categoría.":mode==="cadena"?"Empieza con la letra mostrada. El árbitro valida la respuesta.":"Empieza con la letra mostrada.";$('bp-chain-wrap').hidden=mode!=="cadena";$('bp-chain-answer').value="";$('bp-active').textContent=teams[active];renderScore()}
function effectiveTime(){return mode==="rapido"?Math.max(8,time-Math.max(0,round-1)*3):time}
function startTimer(){clearInterval(timer);endsAt=Date.now()+effectiveTime()*1000;updateTimer();timer=setInterval(()=>{updateTimer();if(Date.now()>=endsAt){clearInterval(timer);timer=null;window.emitSound?.(180,.3,"sawtooth");if(mode==="supervivencia")score[active]-=1;nextRound()}},100)}
function updateTimer(){const left=Math.max(0,Math.ceil((endsAt-Date.now())/1000));$("bp-timer").textContent=left;$("bp-timer-label").textContent=mode==="rapido"?`Rápido · ${effectiveTime()} s`:"Tiempo";$("bp-timer").style.color=left<=5?"var(--danger)":""}
function renderScore(){$("bp-round").textContent=`Ronda ${round} de ${rounds}`;$("bp-score").innerHTML=teams.map((t,i)=>`<span class="badge ${i===active?"badge-indigo":""}">${esc(t)}: ${score[i]??0}</span>`).join(" ")}
function startGame(){rounds=Number($("bp-rounds").value);time=Number($("bp-time").value);goal=Number($("bp-goal").value);categoryFilter=$("bp-category-filter").value;const n=Number($("bp-teams").value);teams=Array.from({length:n},(_,i)=>($("bp-team-"+i)?.value.trim()||"Equipo "+(i+1)));score=Array(n).fill(0);round=1;active=0;lastAnswer="";screen("bp-scr-game");newChallenge();startTimer()}
function award(ok){clearInterval(timer);timer=null;if(ok){if(mode==="cadena"){const answer=$("bp-chain-answer")?.value.trim();if(answer)lastAnswer=answer}score[active]+=1;window.emitSound?.(700,.08,"triangle")}else if(mode==="supervivencia"){score[active]-=1;lastAnswer="";window.emitSound?.(240,.12,"sawtooth")}nextRound()}
function nextRound(){clearInterval(timer);timer=null;if(goal>0&&score[active]>=goal){finish();return}if(round>=rounds){finish();return}round++;active=(active+1)%teams.length;screen("bp-scr-game");newChallenge();startTimer()}
function finish(){clearInterval(timer);timer=null;const max=Math.max(...score),winners=teams.map((t,i)=>score[i]===max?t:null).filter(Boolean);$("bp-result-body").innerHTML=`<div class="bp-verdict"><strong>${winners.length>1?"¡Empate!":"¡Ganó "+esc(winners[0])+"!"}</strong><p class="muted">Se jugaron ${round} rondas.</p></div><div class="bp-team-list">${teams.map((t,i)=>`<div class="bp-team-row"><span>${esc(t)}</span><strong>${score[i]} pts</strong></div>`).join("")}</div>`;screen("bp-scr-result")}
function restore(s){if(!s||!s.teams?.length)return false;mode=s.mode||"normal";teams=s.teams;round=s.round||1;rounds=s.rounds||10;time=s.time||30;goal=s.goal||0;active=s.active||0;score=Array.isArray(s.score)?s.score:Array(teams.length).fill(0);current=s.current||null;lastAnswer=s.lastAnswer||"";categoryFilter=s.categoryFilter||"Todas";endsAt=Number(s.endsAt||0);renderTeamInputs();renderCategories();if(s.screen==="bp-scr-game"){screen("bp-scr-game");if(current){$("bp-category").textContent=current.category;$("bp-letter").textContent=mode==="normal"?"":current.letter;$("bp-letter").style.display=mode==="normal"?"none":"block";$("bp-active").textContent=teams[active];$("bp-hint").textContent=mode==="cadena"?"Empieza con la letra mostrada. El árbitro valida la respuesta.":mode==="normal"?"Di una palabra que pertenezca a la categoría.":"Empieza con la letra mostrada.";$('bp-chain-wrap').hidden=mode!=="cadena"}else newChallenge();if(endsAt>Date.now())startTimer();else nextRound()}else if(s.screen==="bp-scr-result")finish();else screen("bp-scr-lobby");return true}
function bind(){renderModes();renderTeamInputs();renderCategories();$("bp-modes").onclick=e=>{const b=e.target.closest("[data-mode]");if(b){mode=b.dataset.mode;renderModes()}};$("bp-teams").onchange=renderTeamInputs;$("bp-category-filter").onchange=e=>categoryFilter=e.target.value;$("bp-start").onclick=startGame;$("bp-top-menu").onclick=()=>window.GameSession?.clear("batalla");$("bp-lobby-menu").onclick=()=>window.GameSession?.clear("batalla");$("bp-result-menu").onclick=()=>window.GameSession?.clear("batalla");$("bp-correct").onclick=()=>award(true);$("bp-wrong").onclick=()=>award(false);$("bp-next").onclick=()=>nextRound();$("bp-end").onclick=finish;$("bp-new").onclick=()=>{window.GameSession?.clear("batalla");location.reload()}}
function init(){bind();window.GameSession?.register(save);const saved=window.GameSession?.load?.("batalla");if(saved)restore(saved);else screen("bp-scr-lobby")}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();return{startGame,finish}})();