const BatallaPalabras=(()=>{const $=id=>document.getElementById(id);let mode="normal",teams=[],round=1,rounds=10,time=30,goal=0,active=0,score=[],timer=null,endsAt=0,current=null;
const modes=[
 {id:"normal",name:"Normal",desc:"Responde cualquier palabra válida de la categoría."},
 {id:"letra",name:"Letra",desc:"Tu respuesta debe empezar con la letra indicada."},
 {id:"cadena",name:"Cadena",desc:"La respuesta debe empezar con la última letra de la anterior."},
 {id:"rapido",name:"Rápido",desc:"Retos cortos y más presión: el tiempo baja en cada ronda."},
 {id:"supervivencia",name:"Supervivencia",desc:"Un fallo resta 1 punto. Mantente arriba hasta el final."}
];
const categories=["Animales","Comida","Países","Ciudades","Objetos de la casa","Profesiones","Deportes","Películas","Series","Música","Personajes","Naturaleza","Tecnología","Transporte","Ropa","Lugares de Colombia","Comida colombiana","Fiestas y tradiciones","Marcas","Videojuegos"];
const letters="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ".split("");
const shuffle=a=>window.Utils?.shuffleArray?[...window.Utils.shuffleArray(a)]:[...a].sort(()=>Math.random()-.5);
const esc=s=>window.Utils?.escapeHTML?window.Utils.escapeHTML(s):String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
function save(screen="bp-scr-lobby"){window.GameSession?.save("batalla",{mode,teams,round,rounds,time,goal,active,score,endsAt,current,screen,savedAt:Date.now()})}
function screen(id){["bp-scr-lobby","bp-scr-game","bp-scr-result"].forEach(x=>$(x).hidden=x!==id);save(id)}
function renderModes(){ $("bp-modes").innerHTML=modes.map(m=>`<button type="button" class="bp-mode ${m.id===mode?"selected":""}" data-mode="${m.id}"><strong>${m.name}</strong><small>${m.desc}</small></button>`).join("");}
function renderTeamInputs(){const n=Number($("bp-teams").value);$("bp-team-inputs").innerHTML=Array.from({length:n},(_,i)=>`<label>Equipo ${i+1}<input id="bp-team-${i}" maxlength="22" value="${esc(teams[i]||"Equipo "+(i+1))}" placeholder="Nombre del equipo"></label>`).join("");}
function newChallenge(){const category=categories[Math.floor(Math.random()*categories.length)];const letter=letters[Math.floor(Math.random()*letters.length)];current={category,letter,chainLast:""};if(mode==="cadena"&&window.__bpLastAnswer)current.letter=window.__bpLastAnswer.slice(-1).toUpperCase();$("bp-category").textContent=category;$("bp-letter").textContent=mode==="normal"?"":current.letter;$("bp-letter").style.display=mode==="normal"?"none":"block";$("bp-hint").textContent=mode==="normal"?"Di una palabra que pertenezca a la categoría.":mode==="cadena"?"Empieza con la última letra indicada.":"Empieza con la letra mostrada.";$("bp-active").textContent=teams[active];}
function startTimer(){clearInterval(timer);endsAt=Date.now()+time*1000;updateTimer();timer=setInterval(()=>{updateTimer();if(Date.now()>=endsAt){clearInterval(timer);timer=null;window.emitSound?.(180,.3,"sawtooth");score[active]-=mode==="supervivencia"?1:0;nextRound();}},100)}
function updateTimer(){const left=Math.max(0,Math.ceil((endsAt-Date.now())/1000));$("bp-timer").textContent=left;$("bp-timer").style.color=left<=5?"var(--danger)":""}
function startGame(){rounds=Number($("bp-rounds").value);time=Number($("bp-time").value);goal=Number($("bp-goal").value);const n=Number($("bp-teams").value);teams=Array.from({length:n},(_,i)=>($("bp-team-"+i)?.value.trim()||"Equipo "+(i+1)));score=Array(n).fill(0);round=1;active=0;window.__bpLastAnswer="";screen("bp-scr-game");newChallenge();startTimer();}
function award(ok){clearInterval(timer);timer=null;if(ok){score[active]+=1;window.emitSound?.(700,.08,"triangle")}else if(mode==="supervivencia"){score[active]-=1;window.emitSound?.(240,.12,"sawtooth")}nextRound();}
function nextRound(){clearInterval(timer);timer=null;if(goal>0&&score[active]>=goal){finish();return}if(round>=rounds){finish();return}round++;active=(active+1)%teams.length;screen("bp-scr-game");newChallenge();startTimer();}
function finish(){clearInterval(timer);timer=null;const max=Math.max(...score);const winners=teams.map((t,i)=>score[i]===max?t:null).filter(Boolean);$("bp-result-body").innerHTML=`<div class="bp-verdict"><strong>${winners.length>1?"¡Empate!":"¡Ganó "+esc(winners[0])+"!"}</strong><p class="muted">Puntuación final después de ${round} rondas.</p></div><div class="bp-team-list">${teams.map((t,i)=>`<div class="bp-team-row"><span>${esc(t)}</span><strong>${score[i]} pts</strong></div>`).join("")}</div>`;screen("bp-scr-result");}
function restore(s){if(!s||!s.teams?.length)return false;mode=s.mode||"normal";teams=s.teams;round=s.round||1;rounds=s.rounds||10;time=s.time||30;goal=s.goal||0;active=s.active||0;score=Array.isArray(s.score)?s.score:Array(teams.length).fill(0);current=s.current;endsAt=Number(s.endsAt||0);renderTeamInputs();if(s.screen==="bp-scr-game"){screen("bp-scr-game");newChallenge();if(endsAt>Date.now())startTimer();else nextRound();}else if(s.screen==="bp-scr-result"){finish()}else screen("bp-scr-lobby");return true}
function bind(){renderModes();renderTeamInputs();$("bp-modes").onclick=e=>{const b=e.target.closest("[data-mode]");if(!b)return;mode=b.dataset.mode;renderModes();};$("bp-teams").onchange=renderTeamInputs;$("bp-start").onclick=startGame;$("bp-correct").onclick=()=>award(true);$("bp-wrong").onclick=()=>award(false);$("bp-next").onclick=()=>nextRound();$("bp-end").onclick=finish;$("bp-new").onclick=()=>{window.GameSession?.clear("batalla");location.reload()};}
function init(){bind();const saved=window.GameSession?.load?.("batalla");if(saved)restore(saved)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();return{startGame,finish};})();