/* DB independiente para Duelo y Apuesta. */
const AMS_NEW_GAMES_DB = {
  duelo:{questions:[
    ["¿Cuál es el planeta más grande del sistema solar?",["Mercurio","Júpiter","Marte","Venus"],1],
    ["¿Cuántos lados tiene un hexágono?",["5","6","7","8"],1],
    ["¿Cuál es la capital de Colombia?",["Medellín","Cali","Bogotá","Cartagena"],2],
    ["¿Cuál es el océano más grande?",["Atlántico","Índico","Pacífico","Ártico"],2],
    ["¿Qué planeta es conocido como el planeta rojo?",["Venus","Marte","Júpiter","Saturno"],1],
    ["¿Cuál es el símbolo químico del oro?",["Ag","Au","Fe","O"],1],
    ["¿Qué órgano bombea la sangre?",["Pulmón","Cerebro","Corazón","Hígado"],2],
    ["¿Cuál es la unidad básica de la vida?",["Átomo","Célula","Tejido","Órgano"],1],
    ["¿Qué fuerza atrae los objetos hacia la Tierra?",["Fricción","Gravedad","Magnetismo","Presión"],1],
    ["¿Cuántos planetas hay en el sistema solar?",["7","8","9","10"],1],
    ["¿Cuál es la flor nacional de Colombia?",["Rosa","Orquídea","Girasol","Clavel"],1],
    ["¿Cuál es el ave nacional de Colombia?",["Cóndor de los Andes","Águila","Guacamaya","Tucán"],0],
    ["¿Cuál es la capital de Antioquia?",["Cali","Medellín","Pereira","Manizales"],1],
    ["¿Qué ciudad colombiana es famosa por su ciudad amurallada?",["Cartagena","Bogotá","Cúcuta","Ibagué"],0],
    ["¿Cuál es la capital del Valle del Cauca?",["Palmira","Buenaventura","Cali","Tuluá"],2],
    ["¿Qué personaje vive en una piña debajo del mar?",["Mickey","Bob Esponja","Shrek","Garfield"],1],
    ["¿Qué saga tiene a Pikachu?",["Mario","Pokémon","Zelda","Sonic"],1],
    ["¿Cómo se llama el héroe de Hyrule?",["Link","Mario","Kirby","Samus"],0],
    ["¿Qué videojuego usa bloques que caen para completar líneas?",["Tetris","Minecraft","FIFA","Roblox"],0],
    ["¿Qué familia protagoniza Encanto?",["Los Madrigal","Los Increíbles","Los Parr","Los Rivera"],0],
    ["¿Qué superhéroe es conocido como el Hombre Araña?",["Batman","Superman","Spider-Man","Flash"],2],
    ["¿Qué juego popular tiene impostores?",["Among Us","Fortnite","Tetris","Pong"],0],
    ["¿Qué personaje usa el martillo Mjolnir?",["Thor","Hulk","Iron Man","Flash"],0],
    ["¿Qué fontanero protagoniza Super Mario?",["Luigi","Mario","Wario","Toad"],1],
    ["¿Qué película tiene a Woody y Buzz?",["Toy Story","Coco","Up","Cars"],0],
    ["¿Qué gas necesitamos principalmente para respirar?",["Oxígeno","Helio","Hidrógeno","Neón"],0],
    ["¿Qué parte de la planta absorbe agua del suelo?",["Flor","Raíz","Fruto","Hoja"],1],
    ["¿Qué estado del agua es el hielo?",["Líquido","Gas","Sólido","Plasma"],2],
    ["¿Qué planeta está más cerca del Sol?",["Venus","Mercurio","Marte","Tierra"],1],
    ["¿Qué sentido usamos para escuchar?",["Vista","Oído","Tacto","Gusto"],1]
  ]},
  apuesta:{questions:[
    ["¿Cuál es la capital de Colombia?",["Bogotá","Medellín"],0],
    ["¿Cuál es la flor nacional de Colombia?",["Orquídea","Rosa"],0],
    ["¿Cuál es el ave nacional de Colombia?",["Cóndor de los Andes","Águila"],0],
    ["¿Qué ciudad tiene el apodo de Ciudad de la Eterna Primavera?",["Medellín","Cali"],0],
    ["¿Dónde está Monserrate?",["Bogotá","Cartagena"],0],
    ["¿Cuál es la capital del Atlántico?",["Barranquilla","Santa Marta"],0],
    ["¿Cuál es la capital del Valle del Cauca?",["Cali","Pereira"],0],
    ["¿Qué océano es el más grande?",["Pacífico","Atlántico"],0],
    ["¿Cuál es el planeta más grande?",["Júpiter","Saturno"],0],
    ["¿Cuál es el país más grande por territorio?",["Rusia","Canadá"],0],
    ["¿Cuál es la capital de Francia?",["París","Roma"],0],
    ["¿Cuál es la capital de Japón?",["Tokio","Kioto"],0],
    ["¿Qué país tiene forma de bota?",["Italia","Grecia"],0],
    ["¿Dónde están las pirámides de Guiza?",["Egipto","México"],0],
    ["¿Qué planeta es conocido como el planeta rojo?",["Marte","Venus"],0],
    ["¿Qué órgano bombea la sangre?",["Corazón","Pulmón"],0],
    ["¿Cuántos planetas hay en el sistema solar?",["8","9"],0],
    ["¿Qué fuerza atrae los objetos hacia la Tierra?",["Gravedad","Fricción"],0],
    ["¿Qué estado tiene el agua congelada?",["Sólido","Líquido"],0],
    ["¿Qué estrella está más cerca de la Tierra?",["El Sol","Sirio"],0],
    ["¿Cuántos lados tiene un triángulo?",["3","4"],0],
    ["¿Qué personaje vive en una piña bajo el mar?",["Bob Esponja","Mickey"],0],
    ["¿Qué saga tiene a Pikachu?",["Pokémon","Mario"],0],
    ["¿Cómo se llama el héroe de Hyrule?",["Link","Mario"],0],
    ["¿Qué familia protagoniza Encanto?",["Los Madrigal","Los Increíbles"],0],
    ["¿Qué superhéroe es conocido como el Hombre Araña?",["Spider-Man","Batman"],0],
    ["¿Qué juego popular tiene impostores?",["Among Us","Tetris"],0],
    ["¿Qué fontanero protagoniza Super Mario?",["Mario","Luigi"],0],
    ["¿Qué película tiene a Woody y Buzz?",["Toy Story","Cars"],0],
    ["¿Cuál de estos animales es mamífero?",["Delfín","Tiburón"],0],
    ["¿Cuál es la moneda de Colombia?",["Peso colombiano","Sol peruano"],0],
    ["¿Qué órgano usamos principalmente para ver?",["Los ojos","Las orejas"],0],
    ["¿En qué continente está Brasil?",["América del Sur","Europa"],0],
    ["¿Cuál es el idioma oficial de Brasil?",["Portugués","Español"],0],
    ["¿En qué continente está Egipto?",["África","Oceanía"],0],
    ["¿Qué instrumento musical tiene teclas?",["Piano","Violín"],0],
    ["¿Cuánto es 7 + 5?",["12","13"],0],
    ["¿Qué instrumento sirve para medir la temperatura?",["Termómetro","Barómetro"],0],
    ["¿Cuál de estos animales pone huevos?",["Gallina","Perro"],0]
  ]}
};

window.AMS_NEW_GAMES_DB = AMS_NEW_GAMES_DB;
